version: '3'
services:
    ethereum: # GETH
        image: ethereum/client-go:v1.10.13
        ports:
            - '8545:8545'
            - '30303:30303'
        command: --dev --nousb --ws --ws.addr "0.0.0.0" --ws.origins "*" --http --http.vhosts "*" --http.addr "0.0.0.0" --http.corsdomain "*" --miner.gasprice 1000000000 --dev.period 0 --rpc.allow-unprotected-txs

    postgres:
        image: postgres:9.6.17
        ports:
            - '5432:5432'
        command: ['postgres', '-cshared_preload_libraries=pg_stat_statements', '-cmax_connections=200']
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./docker-data:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_MULTIPLE_DATABASES="graph-node","explorer"
            - POSTGRES_USER=dbowner
            - POSTGRES_PASSWORD=let-me-in
            - PGDATA=/tmp

    blockscout:
        image: wighawag/blockscout:v0.0.1
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '4000:4000'
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545
            ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545
            #ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545
            ETHEREUM_JSONRPC_VARIANT: ganache
            DATABASE_URL: postgresql://dbowner:let-me-in@postgres:5432/explorer?ssl=false
        entrypoint: '/bin/sh -c "mix do ecto.create, ecto.migrate; mix phx.server"'
